---
name: Trigger
on:
  push:
  workflow_dispatch:
jobs:
  Send_push:
    runs-on:
      - self-hosted
    steps:
      - name: Trigger
        run: |
         curl -X POST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
         'https://api.github.com/repos/lekx/tgbot_cicd/actions/workflows/main.yaml/dispatches' \
         -H "Accept: application/vnd.github.everest-preview+json" \ 
         -H "Content-Type: application/json" \
           --data '{"ref": "main"}'
