---            
name: Trigger_dev
on:
  push:
    branches:
      - 'dev*'
  workflow_dispatch:
jobs:
  Send_push:
    runs-on:
      - self-hosted
    steps:
      - name: Trigger
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'lek-x',
              repo: 'tgbot_cicd',
              workflow_id: 'build_dev.yaml',
              ref: 'main'
            })
